### ISSUE TITLE
modmailbot

### ISSUE THREAD

**Issue by Killer20025** [Dragory/modmailbot#130]
I have the bot set but every time someone writes the bot a new channel is created why?
can you hide the channel from usern?

**Comment by Dragory** [comment]
This is on purpose. Everyone messaging the bot gets their own channel on the inbox server. Non-staff users wouldn't be able to see this channel since it's on an entirely different server (created in step 3 of setup).

That being said, if you want to use the same server as both the "main" and "inbox" (mail) server, you can do so by following the instructions here: https://github.com/Dragory/modmailbot/issues/99#issuecomment-408471013
