### ISSUE TITLE
Option to use embeds in bot messages to the user

### ISSUE THREAD

**Issue by frostylosty** [Dragory/modmailbot#205]

**Comment by Dragory** [comment]
Can you elaborate on what you mean by "auto embed"?

Also, I don't have a Discord server for the bot because I don't generally offer real-time (i.e. chat) support for the bot, at least not at this time. I simply don't have the time for it.

**Comment by Drakizora** [comment]
I think they're referring to having the bot reply in this format:
![image](https://user-images.githubusercontent.com/46852873/51440519-14bb4480-1c96-11e9-87f9-a3417c112da0.png)
(and I would also like to know if this is possible)

**Comment by Dragory** [comment]
It is not currently possibly, no. Were you interested in having this for the auto-reply (when the user first contacts modmail), for staff replies, and/or for the user's messages?

**Comment by Drakizora** [comment]
Auto and staff reply (so messages the bot sends in dms)

**Comment by JulianP0713** [comment]
What is the point of this though? Embeds make it impossible to copy text on mobile, look bad, have no benefits, and just break things.

**Comment by Devilishhh** [comment]
Is it possible in creating a embed command so it would do it automatically

**Comment by Devilishhh** [comment]
Is it possible in creating a embed command so it would do it automatically

**Comment by mesub7** [comment]
The bot currently doesn't support embeds. While it could be made a feature, it's not really the best. On Android (maybe iOS), you can't copy all the text. Additionally, there's this bug that makes the embed shrink and it looks really bad. 

So in my opinion (and the opinions of others), embeds are "aesthetically pleasing" but bring in more problems rather than solving them.

(If you weren't aware, there's another modmail bot that does embeds, https://github.com/kyb3r/modmail)

**Comment by Eegras** [comment]
For the embeds, there is a plugin now.  https://github.com/MMPlugins/EmbedMessages
