### ISSUE TITLE
Add support for providing config values from environment variables

### ISSUE THREAD

**Issue by karl-police** [Dragory/modmailbot#231]
Can you add config vars for Heroku, please?

**Comment by Dragory** [comment]
The documentation is currently mostly platform agnostic, and will probably stay that way since my aim isn't to provide official support for hosting the bot on specific platforms - the bot should work anywhere node and sqlite do, and other platform specific differences are out of the scope of this repository. You can check issues #74 and #119 for discussion/details about hosting on Heroku.

**Comment by Dragory** [comment]
Unless, of course, you mean more generically reading config values from environment variables. If that is what you meant, I'll reopen this and edit the title!

**Comment by karl-police** [comment]
Thats what I meant

**Comment by karl-police** [comment]
> Unless, of course, you mean more generically reading config values from environment variables. If that is what you meant, I'll reopen this and edit the title!

I forgot to quote.

**Comment by mesub7** [comment]
It's been possible for a while now 👌
