### ISSUE TITLE
Allow sorting of file type into discord channel and local

### ISSUE THREAD

**Issue by DarkView** [Dragory/modmailbot#259]
Hello!

We ran into the issue that log files sent to ModMail over the size of 8MB cant be uploaded by the bot to the attachment storage channel since it doesnt have Nitro. It would be nice to have it sort files by extension.
E.g. .log and .txt are in a whitelist for local storage:
`<name>.log` -> local
`<name>.png` -> attachment channel

Regards

**Comment by imPoggers** [comment]
+1

**Comment by Dragory** [comment]
Instead of sorting by file type, would it not make more sense to use local attachments for any files >8MB? I'll label this as a feature request, but it's not a top priority right now. In the meantime, I would recommend asking users to zip the log file (should hopefully bring it under 8MB) or upload it elsewhere (e.g. Google Drive).

**Comment by DarkView** [comment]
Great! Yeah, that makes sense as well. I just feel that this would be good in any implementation if you have limited space on the server running the bot.
Thanks and regards
