### ISSUE TITLE
Public?

### ISSUE THREAD

**Issue by WhiteRiderSSB** [Dragory/modmailbot#306]
Is it possible to make this a public bot? Or can you code a version that can be public. That would be much appreciated.

**Comment by Dragory** [comment]
No, sorry.

Since the bot has no way of knowing which server you're messaging it from, it would have to ask each user which server's staff they want to message (out of a potential list of up to 100, which is the user's server limit). It would also not allow you to have modmail threads open with multiple servers at the same time (since you only have 1 DM thread with the bot). Due to these UX constraints I'm currently not interested in making a publically inviteable version of the bot.
