### ISSUE TITLE
Logs not created

### ISSUE THREAD

**Issue by Dezyox** [Dragory/modmailbot#317]
So, I don’t know why, but when I close a thread, I stop the bot, I check the logs file, and there is nothing in ! But, the bot know there is older thread with user (When we open a new thread)

It’s probably because it’s missing permission, because I am on Raspbian Lite, I don’t know... 
On the last version
Port 8890 opened
URL set, can’t find my address IP if not set

**Comment by sporkwitch** [comment]
You click the link, you mean? If the bot is not running, the logs are not accessible. The bit hosts a simple files server to hand up the text file. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Dezyox** [comment]
For sure he are running when I open the link !

**Comment by Dragory** [comment]
The `logs` folder is only included in the repository for backwards compatibility (since old versions of the bot used that folder, and removing it from the repository could delete old logs people still have stored there). The actual logs are saved in the database, which is located in `db/data.sqlite`.
