### ISSUE TITLE
Error: Query timed out at DNS._ontimeout

### ISSUE THREAD

**Issue by AlexGaming11** [Dragory/modmailbot#333]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\SAMSUNG\Desktop\modmailbot-master\src>npm start
Loading plugins...
Loaded 14 plugins (14 built-in plugins, 0 external plugins)
Connecting to Discord...
Connected! Now listening to DMs.
Closing thread e4fc7213-8f4b-44d8-92eb-4b961c8b24f3
Deleting channel 609233443645030410
Error: Query timed out
    at DNS._ontimeout (C:\Users\SAMSUNG\Desktop\modmailbot-master\node_modules\d
ns-socket\index.js:98:18)
    at Timeout.ontimeout (C:\Users\SAMSUNG\Desktop\modmailbot-master\node_module
s\dns-socket\index.js:52:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

C:\Users\SAMSUNG\Desktop\modmailbot-master\src>

OMG PLS HELP ME!!!!! WHEN I CLOSE AND TRY TO OPEN A TICKET AGAIN ITS NOT WORKING!!

**Comment by sporkwitch** [comment]
1) don't host things on Windows. Even Microsoft hosts critical systems on Linux because it actually works.

2) the error message told you how to fix it. It's a DNS timeout. Your router, probably the pile of crap your isp is charging an extra monthly fee for, isn't responding or able to find a valid answer. In short, the problem is your LAN and/or computer, not the bot. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Dragory** [comment]
Like @sporkwitch mentioned, this is generally a network error of some sort. I think this error usually stems from the `public-ip` package, so try setting the `url` config.json option to `"http://123.123.123.123"` where "123.123.123.123" is your IP address from e.g. http://ip4.me/.

**Comment by sporkwitch** [comment]
If you're hosting on your own machine, localhost or 127.0.0.1 will also work, though only accessible from the machine running it.
