### ISSUE TITLE
Strike system

### ISSUE THREAD

**Issue by NicoRazor** [Dragory/modmailbot#347]
a !strike command for inside modmail threads for user for example messaging the bot for no real reason or whatever. you do !strike
and each time he messages the bot it will say 
This user has 1 previous modmail threads. Use !logs to see them.
and 2 strikes. for whatever reason. would like to see that
keep up the great work

**Comment by sporkwitch** [comment]
This is probably better managed with one of the many extant moderation bots. This is more for contacting staff. I, for one, would tend to want to keep all moderation records centralised, rather than split between modmail and my actual moderation bot. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by ClearlyElevated** [comment]
Agreed. I keep a "Case Files" channel. And a logs channel seperate for the specific reason of wanting to go back later to view it

**Comment by Dragory** [comment]
Like @sporkwitch mentioned, this will probably not be implemented as a first party feature since it's not integral to the purpose of the bot (and that's why I'm also closing this issue). That being said, someone could implement it as a plugin! Take a look at the Plugins section in the README.
