### ISSUE TITLE
Display user ID of user who mentioned bot in the notification

### ISSUE THREAD

**Issue by mmcmd** [Dragory/modmailbot#348]
Currently the bot only prints the username and discriminator of the user who mentioned Moderator Mail. It would be useful to get the user ID of the user in question in order to be able to open a new thread with the user and for other uses as well.

**Comment by sporkwitch** [comment]
Good idea.  It'd be simple enough to have it formatted for a link (<@UID> will create a normal user mention, even if they're not in that server or channel).  Though the PR I have that inserts the message link would also serve mostly the same purpose, since it gives you a direct link to the post in question, where you can then clearly see who posted it anyway.

**Comment by mesub7** [comment]
@mmcmd 
Hi there! It is now possible. You may need to update your installation to see it in the header.
