### ISSUE TITLE
SqLite3@4.1.0 download fail (Cannot find module 'nopt')

### ISSUE THREAD

**Issue by WhiteSkyAngel** [Dragory/modmailbot#388]
Hey! 
I have a problem installing SqLite3.

I specify that I'm under a vps with ubuntu 16.04, with nodejs v12.16.3 and npm v6.14.4 
Here are the logs + screen of the error

[2020-05-19T17_09_50_272Z-debug.log](https://github.com/Dragory/modmailbot/files/4652171/2020-05-19T17_09_50_272Z-debug.log)
![image](https://user-images.githubusercontent.com/44341346/82358347-b081cf80-9a06-11ea-9c54-0fc50b2343a2.png)

Could somebody help me please?
@Dragory

**Comment by rayd3on** [comment]
Hey dude , 

Open **Powershell** - As admin 

Execute these 2 commands - 

`npm install --global --production --vs2015 --add-python-to-path windows-build-tools`

`npm install --global --production --add-python-to-path windows-build-tools node-gyp`

[Checkout my Bot](https://discord.com/oauth2/authorize?client_id=703658853790908456&permissions=1879440497&redirect_uri=https%3A%2F%2Fpassione.tech%2F&response_type=code&scope=identify%20guilds%20bot)

**Comment by Dragory** [comment]
@rayd3on Since they're on Ubuntu, *windows-build-tools* are unlikely to resolve their issue.

@WhiteSkyAngel Can you verify your Node.js version with `node -v`? Are you trying to set up the newest version of the bot?

Sidenote, `better-sqlite3` (which you tried to install in the image there) is not used in the bot and installing it won't fix any issues you might be having when setting up the bot.
