### ISSUE TITLE
Storage API?

### ISSUE THREAD

**Issue by k9lego** [Dragory/modmailbot#389]
Hey, is there a plugin API where I could develop my own storage system but maintain reasonable compatibility with future releases?
I’m interested in setting this up with either MySQL or Firestore (NoSQL) if it’s not too difficult to restructure the data. Problem is I don’t want to continually need to merge with future releases.
Thanks!

**Comment by k9lego** [comment]
Never mind, I see you've used Knex which supports MySQL.

**Comment by Dragory** [comment]
You can use the undocumented option `knex` to set Knex connection options (though only when using `config.json` rather than `config.ini`). Only SQLite is officially supported, but I run the bot in production myself on MariaDB, so it should at the very least remain fully compatible with MySQL/MariaDB.

**Comment by lumaduda** [comment]
dragory, My thing still wont work.

**Comment by Dragory** [comment]
@lumaduda I'm not sure what you're referring to. Have you opened an issue? Or is it related to this issue?

**Comment by lumaduda** [comment]
Differnt issue,

**Comment by lumaduda** [comment]
Never made a MODMAIL so i am confused, I even checked the docs.
