### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by devrpati0** [Dragory/modmailbot#421]
I can send attachments through modmail but I when a user dms through modmail it sends a link and that link don't work

**Comment by Dragory** [comment]
Both attachments and logs are, by default, served from the bot's host machine directly. This means you'll have to port forward the bot's port (8890 by default) for the links to work. If you're hosting on a rented server, the exact instructions for this would depend on your host. If you're hosting on your own PC, see https://portforward.com/ for per-router instructions. You might also have to double check firewall settings.

You can also change the `attachmentStorage` option to `discord` and set `attachmentStorageChannelId` to a channel ID where the bot can post attachments. Once set, the bot will use Discord links directly rather than hosting the attachments on the bot's machine.

For more help setting up attachments (and logs), please visit the support server at https://discord.gg/vRuhG9R!
