### ISSUE TITLE
Beta on master branch? 

### ISSUE THREAD

**Issue by lostdesign** [Dragory/modmailbot#448]
I was wondering why a beta release is on the master branch. Wouldn't you use "next" or "latest" branch for that?

**Comment by Dragory** [comment]
Most of current development happens on the `dev` branch. I was initially doing this on `master` with the assumption that people would only use the official releases from Releases tab, but then when support requests started appearing from people on the latest `master` commit, I moved development over to the `dev` branch. The `master` branch has barely been updated since.
