### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by antoinegordien** [Dragory/modmailbot#5]
Hello there! 

First, huge thanks for your bot, very usefull :)

There's my issue: bot tells me "NOT ON SERVER" when trying to give the nickname of an user opening a new thread. The thing is that the user is on mainguild server :/

Any ideas? :P

**Comment by Dragory** [comment]
Hey, sometimes the bot don't get member info for every member on the main server. I don't think there's anything I can do about that. You have `mainGuildId` set in `config.json`, right?

**Comment by Dragory** [comment]
Hey, sometimes the bot doesn't get member information for every member on the server, which results in this. I don't think I can do anything to fix it, it's a Discord thing.

Does this happen with every user or just some? And do you have `mainGuildId` specified in `config.json`?

**Comment by shikhir-arora** [comment]
I'll just chime in here and say it could very well be the cache that `discord-js`(and pretty much every library) keeps. Depending on whether the user is new or didn't fall in the cache. The easy way to see if that was the 'issue' is if restarting the bot and reconnecting fixes it. Otherwise, it could be something else - perhaps something with offline user logic? (and thank you from me as well for the great bot) 👍

**Comment by antoinegordien** [comment]
Hey, mainGuildId is specified in config.json, and yes it happen with every user.

I'll to look again, if I can catch any error or not :/

**Comment by Dragory** [comment]
I've started encountering this issue myself as well, and I think I have a solution. Will release a fix soon.

**Comment by Dragory** [comment]
I've released a new update which should fix this. You can update the bot by redownloading the files (or using git).
