### ISSUE TITLE
"!s <snippet>" won't work if the snippet has a big amount of characters.

### ISSUE THREAD

**Issue by Hector1801** [Dragory/modmailbot#514]
To reproduce this bug, follow the next steps:

1. Add a snippet with a lot of characters, so there'll only be free space for one more character.
-> The bot will save the snippet.
2. Run !s <snippet's_name>
-> The bot won't send the message saying "!!<snippet> replies with: ```text```". It basically gets bugged.

**Comment by mesub7** [comment]
This is a discord limitation. Characters for one message are limited to 2000. I'd be surprised if somebody had a tag that long that couldn't be condensed. 

That being said however, I would say it's quite valid (the bot may need to split the snippet into two messages).

**Comment by Hector1801** [comment]
Yes, exactly! In fact, my moderation team has some snippets that are really long, and when they're translated into some specific languages, it's sometimes really hard to make them fit in one single message. I'd say it would be good if the snippet would get divided into two messages, as you said; so this Discord limitation "bug" would get fixed. :)

**Comment by Gugu7264** [comment]
Even if that should be fixed, I won't say it's a major bug because it's discord limitation, that means your snippets are almost reaching the chars limit. That being said, I think what should be fixed isn't the `!s <snippet>` command, but when you create a new snippet, it should be limited to, let's say 1900 chars. Why? Because when the bot sends the snippet to the user, there's not only the snippet but also some information about who sends the messages etc. (hope you understand what I mean)

**Comment by Hector1801** [comment]
Anyway, a good solution for this is simply making the response to get split up into 2 different messages. :P
