### ISSUE TITLE
[Suggestion] Auto close ticket feature

### ISSUE THREAD

**Issue by Derek-Da-Dingo** [Dragory/modmailbot#523]
It happened quite often when a user who 'submitted a ticket' to ModMail regarding an issue 'can be self-resolved' or 'not related to our end' after they read the greeting and the notes like, "Hello... We can assist you with discord channel issues only, please visit XXXXX for hacker report or account related issues".

Would that be better if an user type in ONE WORD (just one word, not a full sentence) 'Resolved', the system will be able to close the ticket automatically in (let's say, 2 hours), **requested** by the 'user', without the needs of server moderators to type in '!close 10m' in order to close the ticket manually.

Not sure whether this suggestion is useful or not. The good outcome is to reduce the workload from the server moderators when dealing with 'non discord related issues'. The worse case scenario is people may abuse the system.

**Comment by MatthewM** [comment]
In all honesty, I'm not sure how I feel about this personally. I like the idea of a user being able to request the closure of the ticket but I wouldn't want them to be able to close a ticket. The reason is that we can open a ticket to the user for a matter that might require Mod / Admin intervention. Say the user has been accused of something by another user and we're trying to get both sides using ModMail rather than DMs so it stays within the entire Staff team that should see it.

**Comment by DarkView** [comment]
You can set `allowUserClose` to enabled and the user will be able to use the ` !close` command to close the ticket from their end.
