### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Girtablulu** [Dragory/modmailbot#55]
I have some stuff which would be handy to have inside the modmail, but overall you did some nice work and it helps us a lot with our +200 moderation/mail contacts per day at the moment :) 

- getting the log information automatically without having first to type !logs 

- Stats about the Modmail (Total/Month/Week/Day mail amount, moderators stats, and what else I cannot think about) 

- Better overview of the !snippets command, maybe with a preview if possible what's actually the snippet is about? 

- Block/Flag certain user names

- Min account Age for Contacting the Modmail

- Automatically closing open mails after x minutes

**Comment by Dragory** [comment]
Hey, thank you for the suggestions! The last point, automatically closing open mails after x minutes, is coming soon. For the rest:

1) I could add a setting that automatically shows the last 2 or 3 logs, or logs from the past week, when the thread opens. How's that sound?

2) After I merge the experimental branch with master (today/tomorrow), this should be easy to implement (since all data is being moved to an sqlite database). I've just dealt with this with some bash scripts myself until now.

3) Definitely. Ideally I'd like to have a web interface of some sort for snippets, but I'll need to work on that some more before I get to it (add a discord login for one, so it's not all public if you know the URL).

4 & 5) Great ideas, shouldn't be too hard to implement either. I'll look into these soon.

**Comment by Girtablulu** [comment]
the last 2-3 logs should be enough, so we can see the most reason once, should be there more I still can run !logs and the rest sounds great, looking forward to it.

**Comment by Girtablulu** [comment]
as I saw you added the function newThreadCategoryId, is it possible to code that the autoclose system is ignoring any mail which is still inside this category, to prevent closing from still opening tickets

**Comment by Dragory** [comment]
The way I was thinking about automatically closing was that moderators could do `!close 1h` and the ticket would be closed in 1 hour *unless* someone posts in the thread.

**Comment by iilukas** [comment]
Any update on this? @dragory
