### ISSUE TITLE
Bug / Issue : Logs Not Working

### ISSUE THREAD

**Issue by EAZYBLACK** [Dragory/modmailbot#558]
I Click The Link For Log And It Says The website cannot be reached

**Comment by mesub7** [comment]
Make sure the bot is running when trying to view log links. If the logs still don't work, the problem is usually that the log viewer's port needs to be forwarded. If you're running the bot on your own PC, check https://portforward.com/ for instructions on how to do this. If you're running the bot on a VPS, your host can help you get started. The port that needs to be forwarded in Modmail Bot's case (assuming default settings) is TCP **8890**.

If you require further support then please visit the [support server](https://discord.gg/vRuhG9R).

**Comment by EAZYBLACK** [comment]
oh i know how to foward but how to see in my local pc without fowarding ? i tried localhost

**Comment by mesub7** [comment]
You'll need to open the port in your firewall.

**Comment by EAZYBLACK** [comment]
TCP or UDP

**Comment by mesub7** [comment]
TCP.

**Comment by EAZYBLACK** [comment]
**Ok Thx Bye**
