### ISSUE TITLE
[RFC] Stickers

### ISSUE THREAD

**Issue by Lagicrus** [Dragory/modmailbot#621]
I apologise if this is the wrong place, but I was wondering what the plan was, or if it was already dealt with, in regards to Stickers.

What happens when a Staff member or the User being DM'd, sends a sticker as a response? What is the plan in this scenario, whether it is to error out or upload it to an external place so it can be "linked in" and rendered correctly?
Also, what is the idea with exporting to an archive with stickers when they are just added to in the mod thread (and not sent), so during the general conversation?

Thanks

**Comment by Dragory** [comment]
Currently, if a user sends a sticker to the bot, it is delivered as text: `<Message contains sticker "sticker name here">`. Replying with stickers is not currently supported.

This support could definitely be extended to support stickers in staff chat messages and replies as well. Unfortunately we can't replace them with a link like we do with attachments because some stickers are not regular images.

**Comment by Lagicrus** [comment]
That makes perfect sense, thanks
