### ISSUE TITLE
Bot can stop responding to commands in threads

### ISSUE THREAD

**Issue by WalkerOfDarkness** [Dragory/modmailbot#671]
On our server we had some open threads and the bot stopped responding to commands like `reply` and `close`.
If you could add a command like `fix` that would allow these commands to start working again it would be very useful because we had to open new threads with all the users.

**Comment by DarkView** [comment]
This only happens if the database the bot uses gets wiped for some reason.
If you manually deleted the database, don't do that.
If you are hosting your bot on a platform like repl.it, the issue occurs because of that. Platforms like repl are **not** made for production hosting and reset all data every time they restart.
