### ISSUE TITLE
hi i dont have logs 

### ISSUE THREAD

**Issue by LLouisplayz** [Dragory/modmailbot#687]
if i open the link `This page isn’t working` and the port is open

**Comment by mesub7** [comment]
Hello.
Make sure the bot is running when trying to view log links. If the logs still don't work, the problem is usually that the log viewer's port needs to be forwarded. If you're running the bot on your own PC, check [here](https://portforward.com/) for instructions on how to do this. If you're running the bot on a VPS, your host may help you get started. The port that needs to be forwarded in Modmail Bot's case (assuming default settings) is TCP **8890**.

For faster support, you may want to visit the [discord server](https://discord.gg/vRuhG9R).

**Comment by LLouisplayz** [comment]
So it can only work on the port because I set it to a other port + the port
is open

Op zo 16 jan. 2022 22:36 schreef David ***@***.***>:

**Comment by LLouisplayz** [comment]
fixted + can you delete this issues plz
