### ISSUE TITLE
Error while replying to user: 500 Internal Server Error on POST /api/v7/channels/943966845415850014/messages

### ISSUE THREAD

**Issue by isaacKenyon** [Dragory/modmailbot#691]
This has happened twice within the last 12 minutes.

- Command used to generate this error: `!r`.
- Commands were to same user.
- User age is 8 months old.
- Error occured on the first and fourth reply back.
- Bot still registered the reply within the message indexing, subsequent replies were incremented by 1.

### Messages that triggered the error:
`!r Could you elaborate?` (First reply)
`!r Np, have a nice time in the server` (Fourth reply)

Bot is running on a Google e2 instance setup with [this](https://github.com/Dragory/modmailbot-community-resources/blob/master/GCP%20Guide.md) guide.

**Comment by DarkView** [comment]
Error code [500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses) are server-side issues and are not caused by the bot itself.
They most likely occurred because Discord was facing issues with their API. If you run into this issue it means *Discord didn't receive the message* so you need to send it again.
